{
 "title": "Blackbox Exporter",
 "description": "Blackbox exporter dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(probe_success{job=~\"$job\"}, instance)"
   },
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "Standort1", "query": "RZ1" },
   { "name": "Standort2", "query": "RZ2" }
  ]
 },
 "panels": [
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", instance=~\"$instance\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\"}[1m])"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort1\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort2\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration Phases",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort1\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "HTTP Probe Duration Phases",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort2\"}) by (phase)",
     "legendFormat": "{{ phase }}"
    }
   ]
  },
  {
   "title": "HTTP Probe Status",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_http_status_code{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort1\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "HTTP Probe Status",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_http_status_code{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort2\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DNS Probe Duration RZ1",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort1\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "DNS Probe Duration RZ2",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort2\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SSL Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_ssl{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort1\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "SSL Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_ssl{job=~\"$job\", instance=~\"$instance\", standort=\"$Standort2\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  }
 ]
}